# GCP cloud build for production
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "australia-southeast1"
  _REPO: "spendwise"
  _CLUSTER: "spendwise-k8s-cluster"
  _LOCATION: "australia-southeast1-b"
  _NAMESPACE: "production"

steps:
  # --- BUILD IMAGES WITH SHA, PUSH IMAGES TO ARTIFACT REGISTRY, APPLY CHANGES TO GKE --- #
  # Account
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/account:${SHORT_SHA}',
      './backend/account_service'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/account:${SHORT_SHA}'
    ]
    
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=k8s/cloudbuild/accountsvc-deployment.yaml
      - --image=gcr.io/${PROJECT_ID}/account:${SHORT_SHA}
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER}
      - --namespace=${_NAMESPACE}  


  # Expense
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/expense:${SHORT_SHA}',
      './backend/expense_service'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/expense:${SHORT_SHA}'
    ]

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=k8s/cloudbuild/expensesvc-deployment.yaml
      - --image=gcr.io/${PROJECT_ID}/expense:${SHORT_SHA}
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER}
      - --namespace=${_NAMESPACE}  

  # Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}',
      './frontend'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
    ]
    
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=k8s/cloudbuild/frontendsvc-deployment.yaml
      - --image=gcr.io/${PROJECT_ID}/frontend:${SHORT_SHA}
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER}
      - --namespace=${_NAMESPACE}  

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/account:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/expense:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'