name: Docker Image CI

on:
  push:
    branches: [ "test-cicd" ]
  pull_request:
    branches: [ "test-cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        run: |
          docker build -t tut888/sit737-account-service:${{ github.sha }} ./account_service
          docker push tut888/sit737-account-service:${{ github.sha }}
