name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  GKE_CLUSTER: simple-k8s-cluster
  GKE_ZONE: australia-southeast1-b
  DEPLOYMENT_NAME: accountsvc-deployment
  CONTAINER_NAME: accountsvc-container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # - name: Install dependencies and run test
      #   run: | 
      #     npm install
      #     npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t tut888/sit737-account-service:${{ github.sha }} ./account_service
          docker push tut888/sit737-account-service:${{ github.sha }}
      
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      
      # Deploy updated image to GKE
      - name: Deploy updated image to GKE
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --location=${{ env.GKE_ZONE }}
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=tut888/sit737-account-service:${{ github.sha }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}