name: Docker Image CI - Account Sevice

on:
  push:
    branches: [ "develop" ]
    paths:
      - "account_service/**"
      - ".github/workflows/docker-image-accountsvc.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Start MongoDB container
        run: docker run -d -p 27017:27017 --name test-mongo mongo:6
      
      # Test
      - name: Run account service
        env:
          PORT: 3030
          MONGO_URI: mongodb://localhost:27017/spendwise
        run: | 
          cd account_service
          npm run start:test

      - name: Run test for account service
        env:
          PORT: 3030
        run: | 
          cd account_service
          npm install
          npm test
      
      # Containerization
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t tut888/sit737-account-service:autobuild ./account_service
          docker push tut888/sit737-account-service:autobuild
      
      # Below code is not working due to limited permission
      # - uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: {{ secrets.GKE_SA_KEY }}

      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2
      
      # - name: Deploy updated image to GKE
      #   run: |
      #     gcloud container clusters get-credentials simple-k8s-cluster --location=australia-southeast1-b
      #     kubectl set image deployment/accountsvc-deployment accountsvc-container=tut888/sit737-account-service:{{ github.sha }}
      #     kubectl rollout status deployment/accountsvc-deployment